// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAArcJLU-iIRrjnTC3YrH7ChUmx3Dbn_-E',
    appId: '1:855651744303:web:c0c258a31d7168abd3e4da',
    messagingSenderId: '855651744303',
    projectId: 'quranapp-c5d78',
    authDomain: 'quranapp-c5d78.firebaseapp.com',
    storageBucket: 'quranapp-c5d78.appspot.com',
    measurementId: 'G-WC8ZR1PPJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBziMb0QSU6cQ86mugJZRY-JwnIxQq9opw',
    appId: '1:855651744303:android:534ddcad10726cdad3e4da',
    messagingSenderId: '855651744303',
    projectId: 'quranapp-c5d78',
    storageBucket: 'quranapp-c5d78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz24PU3b5WGOHf-8641qfLqMaObeTYEXg',
    appId: '1:855651744303:ios:4c9483d318a3a130d3e4da',
    messagingSenderId: '855651744303',
    projectId: 'quranapp-c5d78',
    storageBucket: 'quranapp-c5d78.appspot.com',
    iosBundleId: 'com.example.quranApp',
  );
}
